#!/bin/sh
here=$(dirname "$0")
cd ${here}
cat \
    ../machine.js \
    > ./machine-bundle.js &&
    echo "module.exports = Machine;" >> ./machine-bundle.js &&
    node ./test-machine.js &&
    rm ./machine-bundle.js
